version: '3.3'

services:
  web:
    build: ./src
    restart: always
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    env_file:
      - ./src/.env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 0
    ports:
      - "5050:80"

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf